"""Version history: every edit kept, and any of them restorable.

Two things make this useful rather than decorative:

* the change summary next to each entry, generated by diffing against the
  parent, because nobody writes a commit message in a web form; and
* restore actually restoring. Governance has no idea what a workflow is, so
  each service registers a function that can apply one of its own snapshots.
  Without that, "restore" would mean handing the user some JSON.
"""

from __future__ import annotations

import uuid
from collections.abc import Callable
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from shared_python.errors import BadRequestError, NotFoundError

from service_governance.diff import diff_snapshots
from service_governance.models import ResourceVersion

# resource_type -> a function that writes a snapshot back onto the live resource.
Restorer = Callable[[Session, uuid.UUID, uuid.UUID, dict[str, Any], uuid.UUID | None], None]
_restorers: dict[str, Restorer] = {}

# resource_type -> a function that reads the live resource as a snapshot.
Snapshotter = Callable[[Session, uuid.UUID, uuid.UUID], dict[str, Any] | None]
_snapshotters: dict[str, Snapshotter] = {}

MAX_VERSIONS_RETURNED = 100


def register_restorer(resource_type: str, restorer: Restorer) -> None:
    _restorers[resource_type] = restorer


def register_snapshotter(resource_type: str, snapshotter: Snapshotter) -> None:
    _snapshotters[resource_type] = snapshotter


def supported_types() -> tuple[str, ...]:
    return tuple(sorted(_snapshotters))


def current_snapshot(
    db: Session, resource_type: str, project_id: uuid.UUID, resource_id: uuid.UUID
) -> dict[str, Any] | None:
    snapshotter = _snapshotters.get(resource_type)
    if snapshotter is None:
        return None
    return snapshotter(db, project_id, resource_id)


def latest_version(db: Session, resource_type: str, resource_id: uuid.UUID) -> ResourceVersion | None:
    return db.scalar(
        select(ResourceVersion)
        .where(
            ResourceVersion.resource_type == resource_type,
            ResourceVersion.resource_id == resource_id,
        )
        .order_by(ResourceVersion.version.desc())
        .limit(1)
    )


def record_version(
    db: Session,
    *,
    project_id: uuid.UUID,
    resource_type: str,
    resource_id: uuid.UUID,
    name: str,
    snapshot: dict[str, Any],
    actor_user_id: uuid.UUID | None = None,
    restored_from_version: int | None = None,
) -> ResourceVersion | None:
    """Store a snapshot, unless nothing actually changed.

    Called from save paths, so it returns None rather than raising when the
    edit was a no-op -- saving a form without touching it should not fill the
    history with identical entries.
    """
    previous = latest_version(db, resource_type, resource_id)

    if previous is not None:
        difference = diff_snapshots(previous.snapshot_json, snapshot)
        if difference.identical and restored_from_version is None:
            return None
        summary = difference.summary()
    else:
        summary = "Created."

    version = ResourceVersion(
        project_id=project_id,
        resource_type=resource_type,
        resource_id=resource_id,
        version=(previous.version + 1) if previous else 1,
        name=name[:200],
        snapshot_json=snapshot,
        change_summary=summary,
        created_by_user_id=actor_user_id,
        restored_from_version=restored_from_version,
    )
    db.add(version)
    db.flush()
    return version


def get_version(
    db: Session, project_id: uuid.UUID, resource_type: str, resource_id: uuid.UUID, version: int
) -> ResourceVersion:
    row = db.scalar(
        select(ResourceVersion).where(
            ResourceVersion.project_id == project_id,
            ResourceVersion.resource_type == resource_type,
            ResourceVersion.resource_id == resource_id,
            ResourceVersion.version == version,
        )
    )
    if row is None:
        raise NotFoundError(f"Version {version} not found.")
    return row


def list_versions(
    db: Session, project_id: uuid.UUID, resource_type: str, resource_id: uuid.UUID
) -> list[ResourceVersion]:
    return list(
        db.scalars(
            select(ResourceVersion)
            .where(
                ResourceVersion.project_id == project_id,
                ResourceVersion.resource_type == resource_type,
                ResourceVersion.resource_id == resource_id,
            )
            .order_by(ResourceVersion.version.desc())
            .limit(MAX_VERSIONS_RETURNED)
        ).all()
    )


def restore_version(
    db: Session,
    *,
    project_id: uuid.UUID,
    resource_type: str,
    resource_id: uuid.UUID,
    version: int,
    actor_user_id: uuid.UUID | None,
) -> tuple[int, str]:
    """Put a resource back the way it was, and record that as a new version.

    Restoring moves history forward rather than truncating it: the rollback is
    itself an edit somebody made, and erasing the versions in between would
    lose the record of what was undone.
    """
    restorer = _restorers.get(resource_type)
    if restorer is None:
        raise BadRequestError(f"'{resource_type}' cannot be restored automatically.")

    target = get_version(db, project_id, resource_type, resource_id, version)
    current = latest_version(db, resource_type, resource_id)
    if current is not None and current.version == version:
        raise BadRequestError("That is already the current version.")

    restorer(db, project_id, resource_id, dict(target.snapshot_json), actor_user_id)

    difference = diff_snapshots(current.snapshot_json if current else None, target.snapshot_json)
    recorded = record_version(
        db,
        project_id=project_id,
        resource_type=resource_type,
        resource_id=resource_id,
        name=target.name,
        snapshot=dict(target.snapshot_json),
        actor_user_id=actor_user_id,
        restored_from_version=version,
    )
    db.commit()

    new_version = recorded.version if recorded else (current.version if current else version)
    return new_version, f"Restored version {version}. {difference.summary()}"


def total_versions(db: Session) -> int:
    return db.scalar(select(func.count(ResourceVersion.id))) or 0
