"""The canonical type system.

Every source maps into :class:`PWType` and it maps out to every destination, so
there are 2N conversions rather than N-squared -- and one place to ask what a
conversion costs.
"""

from shared_python.types.coercion import (
    CastLoss,
    can_cast,
    cast_loss,
    is_exact,
    widen,
)
from shared_python.types.inference import infer_pw_type, to_legacy_name
from shared_python.types.lattice import (
    BOOLEAN,
    BYTES,
    DATE,
    FLOAT32,
    FLOAT64,
    GEOGRAPHY,
    INT8,
    INT16,
    INT32,
    INT64,
    INTERVAL,
    JSON,
    STRING,
    UINT8,
    UINT16,
    UINT32,
    UINT64,
    UNKNOWN,
    UUID,
    Kind,
    PWType,
    array,
    binary,
    decimal,
    from_json,
    mapping,
    parse,
    string,
    struct,
    time,
    timestamp,
    to_json,
)
from shared_python.types.mappings import TypeMapping, get as mapping_for, known as known_dialects

__all__ = [
    "BOOLEAN",
    "BYTES",
    "DATE",
    "FLOAT32",
    "FLOAT64",
    "GEOGRAPHY",
    "INT8",
    "INT16",
    "INT32",
    "INT64",
    "INTERVAL",
    "JSON",
    "STRING",
    "UINT8",
    "UINT16",
    "UINT32",
    "UINT64",
    "UNKNOWN",
    "UUID",
    "CastLoss",
    "Kind",
    "PWType",
    "TypeMapping",
    "array",
    "binary",
    "can_cast",
    "cast_loss",
    "decimal",
    "from_json",
    "infer_pw_type",
    "is_exact",
    "known_dialects",
    "mapping",
    "mapping_for",
    "parse",
    "string",
    "struct",
    "time",
    "timestamp",
    "to_json",
    "to_legacy_name",
    "widen",
]
