#!/usr/bin/env python
"""Regenerate `docs/adding-a-connector.md` from the connector schema.

The field table comes from `Manifest.model_fields`, the tier table from the
`Tier` enum, and the counts from the live registry -- so the guide cannot
describe a schema the code does not have. A test asserts the checked-in file
matches this output, which is what makes running it part of adding a connector.
"""

from __future__ import annotations

import pathlib
import sys

TARGET = pathlib.Path(__file__).resolve().parents[1] / "docs" / "adding-a-connector.md"


def render() -> str:
    import service_connectors  # noqa: F401  -- assembles the catalogue
    from service_connectors.health import overview
    from service_connectors.manifest import MANIFEST_TYPES, Manifest
    from service_connectors.protocol import CATEGORIES, Tier

    report = overview()
    lines: list[str] = []
    add = lines.append

    add("# Adding a connector")
    add("")
    add("There are four ways, and which one you need depends on what you are")
    add("connecting to. None of them involves editing more than one file.")
    add("")
    add(
        f"The catalogue today: **{report.total} connectors**, {report.available} usable "
        f"on this deployment, {report.verified} verified by a test that actually runs "
        f"them. {report.origins.get('manifest', 0)} come from manifests, "
        f"{report.origins.get('dialect', 0)} from the dialect table, "
        f"{report.origins.get('matrix', 0)} from the object-store matrix, "
        f"{report.origins.get('declared', 0)} are engines listed with what to use "
        f"instead, and {report.origins.get('handwritten', 0)} are hand-written."
    )
    add("")
    add("---")
    add("")
    add("## 1. A SaaS API — write a manifest")
    add("")
    add("Drop a YAML file in")
    add("`services/service-connectors/src/service_connectors/manifests/`. That is the")
    add("whole task: no Python, no registration, no frontend change. The file is")
    add("validated when the package imports, so a malformed one fails the build rather")
    add("than shipping.")
    add("")
    add("```yaml")
    add("key: acme_widgets")
    add("label: Acme Widgets")
    add("category: saas")
    add("description: Read widgets and orders from Acme.")
    add("docs_url: https://developers.acme.example/reference")
    add("base_url: https://api.acme.example/v1")
    add("auth:")
    add("  kind: api_key")
    add("  placement: header")
    add("  header: X-Acme-Key")
    add('  template: "{token}"')
    add("streams:")
    add("  - name: widgets")
    add("    path: /widgets")
    add("    records_path: data")
    add("    primary_key: id")
    add("    pagination:")
    add("      kind: cursor")
    add("      cursor_param: cursor")
    add("      cursor_path: meta.next")
    add("    incremental:")
    add("      cursor_field: updated_at")
    add("      param: since")
    add('      template: "{value}"')
    add("    schema:")
    add("      id: { type: STRING }")
    add("      attributes.name: { type: STRING, rename: name }")
    add("      attributes.updated: { type: TIMESTAMP, tz_aware: true, rename: updated_at }")
    add("tier: 4")
    add("```")
    add("")
    add("Then run the connector tests. They will tell you if anything is wrong:")
    add("")
    add("```bash")
    add("pytest services/service-connectors/tests -q")
    add("```")
    add("")
    add("### What each field is for")
    add("")
    add("| Field | Required | Notes |")
    add("|---|---|---|")
    for name, field in Manifest.model_fields.items():
        required = "yes" if field.is_required() else "no"
        add(f"| `{name}` | {required} | {(field.description or '').strip()} |")
    add("")
    add(
        "**Types** a `schema:` block may use: "
        + ", ".join(f"`{entry}`" for entry in MANIFEST_TYPES)
        + "."
    )
    add("They name the Phase 08 type lattice, so `TIMESTAMP` means the platform's")
    add("timestamp with tz-awareness included — not a hint for something later to")
    add("guess at.")
    add("")
    add("**Categories**: " + ", ".join(f"`{entry}`" for entry in CATEGORIES) + ".")
    add("")
    add("### Things the validator will stop you doing")
    add("")
    add("- An unknown key. A typo that silently did nothing is how a connector ships")
    add("  looking fine and paginates only the first page.")
    add("- Cursor pagination without a `cursor_path`.")
    add("- An auth `template` with no `{token}` in it, or an incremental `template`")
    add("  with no `{value}`.")
    add("- Two streams with the same name.")
    add("- A `{placeholder}` in `base_url` or a `path` with no `config_fields` entry")
    add("  to fill it — a connector nobody could configure.")
    add("- Claiming a tier above 4 without saying what verified it.")
    add("")
    add("A config value used in a URL also cannot contain `/`, `?`, `#`, `@`, `:` or")
    add("whitespace. It is a *piece* of a URL, never a place to build one: without")
    add("that rule a subdomain setting could move the request to a host the manifest")
    add("never named, with the credential attached.")
    add("")
    add("---")
    add("")
    add("## 2. A SQL database — add a row to the dialect table")
    add("")
    add("`services/service-connectors/src/service_connectors/dialects.py`. Six lines:")
    add("")
    add("```python")
    add('_d(key="acmedb", label="AcmeDB", driver="acmedb+acmedriver", package="acme-sqlalchemy",')
    add('   default_port=6789, limit_style="fetch_first",')
    add('   description="Read tables from AcmeDB.")')
    add("```")
    add("")
    add("SQLAlchemy does the introspection and the reading, so what a row supplies is")
    add("the URL, the driver package, the connection shape (`SERVER`, `FILE` or")
    add('`ACCOUNT`) and how the dialect spells "give me a few rows".')
    add("")
    add("If the driver is not installed on a deployment, the connector still appears")
    add("and still answers `test()` — with the name of the package to install — and its")
    add("capabilities narrow to `test` alone, so nothing promises a read it cannot do.")
    add("")
    add("---")
    add("")
    add("## 3. An object store — add a row to the store table")
    add("")
    add("`services/service-connectors/src/service_connectors/stores.py`. If the store")
    add("publishes an S3-compatible endpoint, that is all it takes and the result is")
    add("working code:")
    add("")
    add("```python")
    add('_s(Store(key="acme_object", label="Acme Object Storage", kind=S3_COMPATIBLE,')
    add('         description="Read objects from Acme Object Storage.",')
    add('         endpoint_template="https://s3.{region}.acme.example",')
    add('         endpoint_field=ConfigField("region", "Region", default="eu-west-1")))')
    add("```")
    add("")
    add(
        f"Every store reads every format in the registry, so the matrix is "
        f"{report.store_format_combinations:,} store-and-format combinations across "
        f"{report.formats} formats. Adding a format adds it to every store at once."
    )
    add("")
    add("---")
    add("")
    add("## 4. An engine nothing here can drive — declare it, with a way out")
    add("")
    add("`services/service-connectors/src/service_connectors/datastores.py`. Cassandra,")
    add("Redis, HBase and their neighbours each need a client library and their own")
    add("idea of what a row is, so none of them reads anything here yet. They are in")
    add("the catalogue anyway, because omitting Cassandra leaves somebody concluding")
    add("their data is out of reach — and most of these publish a second interface the")
    add("platform *does* read.")
    add("")
    add("```python")
    add('_s(DataStore(key="acme_kv", label="Acme KV", category="nosql",')
    add('             description="Read records from Acme KV.",')
    add('             package="acme-kv-client",')
    add('             instead="Acme KV\'s REST gateway is readable through the REST connector."))')
    add("```")
    add("")
    add("`instead` is required and the dataclass refuses an entry without it: a")
    add("catalogue entry that cannot do anything and cannot say what would is noise.")
    add("Every one of these declares only `test`, reports `available: false`, and")
    add("answers a connection test with the reason.")
    add("")
    add("---")
    add("")
    add("## Verification tiers")
    add("")
    add("Every connector carries one, and it is shown wherever a connector is chosen")
    add("and in the output of any run that used it.")
    add("")
    add("| Tier | Badge | Meaning |")
    add("|---|---|---|")
    for tier in Tier:
        add(f"| {int(tier)} — {tier.label} | {tier.badge} | {tier.explanation} |")
    add("")
    add("The default is 4, deliberately: a connector that forgets to say is described")
    add("as unverified rather than silently promoted.")
    add("")
    add("**A tier above 4 needs a citation.** `verified_by` names a test file, and")
    add("`test_generators.py` checks that the file exists *and* mentions the connector.")
    add("Without that the tier system is decoration — anybody could type `tier: 1` and")
    add('the badge would read "Verified" on something nothing has ever run.')
    add("")
    add("To promote a connector, write the test first, then cite it:")
    add("")
    add("```yaml")
    add("tier: 2")
    add("verified_by: test_acme_widgets.py")
    add("```")
    add("")
    add("---")
    add("")
    add("## Secrets")
    add("")
    add("A config value can be a secret or a *reference* to one:")
    add("")
    add("```")
    add("vault://database/prod#password")
    add("env://ACME_API_KEY")
    add("file:///run/secrets/acme#api_key")
    add("awssm://prod/acme-credentials#api_key")
    add("azurekv://my-vault/acme-api-key")
    add("```")
    add("")
    add("References are stored as pointers and resolved at the point of use. `env` and")
    add("`file` work everywhere; the managed stores register only when their SDK is")
    add("installed, and a reference to one that is not configured **fails loudly**")
    add('rather than falling back — otherwise "our secrets are in Vault" would be a')
    add("sentence nobody could check.")
    add("")
    add("---")
    add("")
    add("## Schema drift")
    add("")
    add("A manifest that declares a `schema:` block is watched: the columns it claims")
    add("are compared with what is there, and a difference is graded `breaking`,")
    add("`risky` or `compatible` by the same code that grades a dataset's drift. A")
    add("manifest with no declared schema has nothing to go stale, and the watch")
    add("reports it as unwatchable rather than as fine.")
    add("")
    add("The watch runs over **configured connections**, not over the catalogue: a")
    add("manifest is a file and cannot change behind your back, whereas the vendor it")
    add("describes changes constantly. `POST /projects/{id}/connectors/watch` runs a")
    add("sweep now, and a schedule of type `connector_schema_watch` runs it nightly on")
    add("the platform's own scheduler. A change files a drift incident — the same")
    add("object a failing quality rule produces, on the same list, with the same")
    add("timeline — and a schema that goes back to normal closes it again.")
    add("")
    add("A connection that cannot be read is reported as skipped, with the reason.")
    add("Treating \"we could not look\" as \"the columns are gone\" would file a")
    add("breaking incident every time a VPN dropped.")
    add("")
    return "\n".join(lines)


def main() -> int:
    fresh = render()
    if TARGET.exists() and TARGET.read_text(encoding="utf-8") == fresh:
        print("docs/adding-a-connector.md is already up to date.")
        return 0
    TARGET.write_text(fresh, encoding="utf-8")
    print(f"Wrote docs/adding-a-connector.md ({len(fresh.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
